"""enterprise domain schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-22 09:51:32.368328
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_login_events_created_at"), "login_events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_login_events_outcome"), "login_events", ["outcome"], unique=False)
    op.create_index(op.f("ix_login_events_tenant_id"), "login_events", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_login_events_user_id"), "login_events", ["user_id"], unique=False)
    op.create_table(
        "permissions",
        sa.Column("permission_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("resource", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("permission_id"),
    )
    op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=True)
    op.create_table(
        "tenants",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_index(op.f("ix_tenants_code"), "tenants", ["code"], unique=True)
    op.create_index(op.f("ix_tenants_status"), "tenants", ["status"], unique=False)
    op.create_table(
        "after_sale_cases",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_no", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.String(length=36), nullable=True),
        sa.Column("case_type", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("requested_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("approved_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("assignee_id", sa.String(length=36), nullable=True),
        sa.Column("sla_due_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("case_id"),
        sa.UniqueConstraint("tenant_id", "case_no", name="uq_after_sale_case_no"),
    )
    op.create_index(
        op.f("ix_after_sale_cases_case_type"), "after_sale_cases", ["case_type"], unique=False
    )
    op.create_index(
        op.f("ix_after_sale_cases_order_id"), "after_sale_cases", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_after_sale_cases_status"), "after_sale_cases", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_after_sale_cases_tenant_id"), "after_sale_cases", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_cases_tenant_status_created",
        "after_sale_cases",
        ["tenant_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "agent_runs",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("intent", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(op.f("ix_agent_runs_tenant_id"), "agent_runs", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_thread_id"), "agent_runs", ["thread_id"], unique=False)
    op.create_table(
        "approval_definitions",
        sa.Column("definition_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("steps_json", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("definition_id"),
        sa.UniqueConstraint("tenant_id", "code", "version", name="uq_approval_def_version"),
    )
    op.create_index(
        op.f("ix_approval_definitions_tenant_id"),
        "approval_definitions",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "approval_records",
        sa.Column("record_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("task_thread_id", sa.String(length=64), nullable=False),
        sa.Column("step_no", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.create_index(
        op.f("ix_approval_records_task_thread_id"),
        "approval_records",
        ["task_thread_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_records_tenant_id"), "approval_records", ["tenant_id"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("external_customer_id", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("email_masked", sa.String(length=255), nullable=True),
        sa.Column("phone_masked", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("customer_id"),
        sa.UniqueConstraint("tenant_id", "external_customer_id", name="uq_customers_external"),
    )
    op.create_index(op.f("ix_customers_tenant_id"), "customers", ["tenant_id"], unique=False)
    op.create_table(
        "evaluation_suites",
        sa.Column("suite_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("suite_id"),
    )
    op.create_index(
        op.f("ix_evaluation_suites_tenant_id"), "evaluation_suites", ["tenant_id"], unique=False
    )
    op.create_table(
        "feature_flags",
        sa.Column("flag_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("flag_key", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("rules_json", sa.Text(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("flag_id"),
        sa.UniqueConstraint("tenant_id", "flag_key", name="uq_feature_flag_key"),
    )
    op.create_index(
        op.f("ix_feature_flags_tenant_id"), "feature_flags", ["tenant_id"], unique=False
    )
    op.create_table(
        "human_handoff_tasks",
        sa.Column("handoff_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("assignee_id", sa.String(length=36), nullable=True),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("handoff_id"),
    )
    op.create_index(
        op.f("ix_human_handoff_tasks_tenant_id"), "human_handoff_tasks", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_human_handoff_tasks_thread_id"), "human_handoff_tasks", ["thread_id"], unique=False
    )
    op.create_table(
        "idempotency_records",
        sa.Column("record_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("response_json", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("record_id"),
        sa.UniqueConstraint(
            "tenant_id", "scope", "idempotency_key", name="uq_idempotency_scope_key"
        ),
    )
    op.create_index(
        op.f("ix_idempotency_records_tenant_id"), "idempotency_records", ["tenant_id"], unique=False
    )
    op.create_table(
        "inbox_events",
        sa.Column("inbox_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("external_event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("inbox_id"),
        sa.UniqueConstraint(
            "tenant_id", "source", "external_event_id", name="uq_inbox_external_event"
        ),
    )
    op.create_index(op.f("ix_inbox_events_tenant_id"), "inbox_events", ["tenant_id"], unique=False)
    op.create_table(
        "knowledge_bases",
        sa.Column("knowledge_base_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("knowledge_base_id"),
    )
    op.create_index(
        op.f("ix_knowledge_bases_tenant_id"), "knowledge_bases", ["tenant_id"], unique=False
    )
    op.create_table(
        "message_attachments",
        sa.Column("attachment_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("attachment_id"),
    )
    op.create_index(
        op.f("ix_message_attachments_message_id"),
        "message_attachments",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_attachments_tenant_id"), "message_attachments", ["tenant_id"], unique=False
    )
    op.create_table(
        "message_feedback",
        sa.Column("feedback_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("feedback_id"),
    )
    op.create_index(
        op.f("ix_message_feedback_message_id"), "message_feedback", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_feedback_tenant_id"), "message_feedback", ["tenant_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("notification_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("recipient_id", sa.String(length=36), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("template_code", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("notification_id"),
    )
    op.create_index(
        op.f("ix_notifications_recipient_id"), "notifications", ["recipient_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_tenant_id"), "notifications", ["tenant_id"], unique=False
    )
    op.create_table(
        "oidc_connections",
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("issuer", sa.String(length=512), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("secret_reference", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("connection_id"),
    )
    op.create_index(
        op.f("ix_oidc_connections_tenant_id"), "oidc_connections", ["tenant_id"], unique=False
    )
    op.create_table(
        "order_addresses",
        sa.Column("order_address_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=32), nullable=False),
        sa.Column("address_type", sa.String(length=32), nullable=True),
        sa.Column("recipient_masked", sa.String(length=128), nullable=True),
        sa.Column("phone_masked", sa.String(length=32), nullable=True),
        sa.Column("address_ciphertext", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("order_address_id"),
    )
    op.create_index(
        op.f("ix_order_addresses_order_id"), "order_addresses", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_addresses_tenant_id"), "order_addresses", ["tenant_id"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("order_item_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=32), nullable=False),
        sa.Column("sku_id", sa.String(length=36), nullable=True),
        sa.Column("sku_code", sa.String(length=128), nullable=True),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("paid_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("refunded_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("order_item_id"),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_items_tenant_id"), "order_items", ["tenant_id"], unique=False)
    op.create_table(
        "order_status_history",
        sa.Column("history_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=32), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_index(
        op.f("ix_order_status_history_order_id"), "order_status_history", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_status_history_tenant_id"),
        "order_status_history",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("available_at", sa.DateTime(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_outbox_available", "outbox_events", ["status", "available_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"), "outbox_events", ["aggregate_id"], unique=False
    )
    op.create_index(op.f("ix_outbox_events_status"), "outbox_events", ["status"], unique=False)
    op.create_index(
        op.f("ix_outbox_events_tenant_id"), "outbox_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "payment_callbacks",
        sa.Column("callback_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("callback_id"),
        sa.UniqueConstraint("provider", "provider_event_id", name="uq_payment_callbacks_event"),
    )
    op.create_index(
        op.f("ix_payment_callbacks_tenant_id"), "payment_callbacks", ["tenant_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("payment_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("merchant_trade_no", sa.String(length=128), nullable=False),
        sa.Column("provider_trade_no", sa.String(length=128), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("refunded_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("payment_id"),
        sa.UniqueConstraint("tenant_id", "merchant_trade_no", name="uq_payments_merchant_no"),
    )
    op.create_index(op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("ix_payments_tenant_id"), "payments", ["tenant_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("product_id"),
    )
    op.create_index(op.f("ix_products_tenant_id"), "products", ["tenant_id"], unique=False)
    op.create_table(
        "quality_rules",
        sa.Column("rule_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("rule_type", sa.String(length=32), nullable=False),
        sa.Column("definition_json", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("rule_id"),
    )
    op.create_index(
        op.f("ix_quality_rules_tenant_id"), "quality_rules", ["tenant_id"], unique=False
    )
    op.create_table(
        "quality_tasks",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("assignee_id", sa.String(length=36), nullable=True),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_quality_tasks_tenant_id"), "quality_tasks", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_quality_tasks_thread_id"), "quality_tasks", ["thread_id"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("role_id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_roles_tenant_code"),
    )
    op.create_index(op.f("ix_roles_tenant_id"), "roles", ["tenant_id"], unique=False)
    op.create_table(
        "shipments",
        sa.Column("shipment_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=32), nullable=False),
        sa.Column("carrier", sa.String(length=64), nullable=True),
        sa.Column("tracking_no", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("shipped_at", sa.DateTime(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("shipment_id"),
        sa.UniqueConstraint("tenant_id", "carrier", "tracking_no", name="uq_shipments_tracking"),
    )
    op.create_index(op.f("ix_shipments_order_id"), "shipments", ["order_id"], unique=False)
    op.create_index(op.f("ix_shipments_tenant_id"), "shipments", ["tenant_id"], unique=False)
    op.create_table(
        "system_configs",
        sa.Column("config_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("config_key", sa.String(length=128), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("is_secret_reference", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("config_id"),
        sa.UniqueConstraint("tenant_id", "config_key", name="uq_system_config_key"),
    )
    op.create_index(
        op.f("ix_system_configs_tenant_id"), "system_configs", ["tenant_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone_masked", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("tenant_id", "username", name="uq_users_tenant_name"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_table(
        "webhook_endpoints",
        sa.Column("endpoint_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("secret_reference", sa.String(length=255), nullable=False),
        sa.Column("event_types_json", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("endpoint_id"),
    )
    op.create_index(
        op.f("ix_webhook_endpoints_tenant_id"), "webhook_endpoints", ["tenant_id"], unique=False
    )
    op.create_table(
        "after_sale_evidence",
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_type", sa.String(length=32), nullable=True),
        sa.Column("object_key", sa.String(length=512), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("submitted_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["after_sale_cases.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("evidence_id"),
    )
    op.create_index(
        op.f("ix_after_sale_evidence_case_id"), "after_sale_evidence", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_after_sale_evidence_tenant_id"), "after_sale_evidence", ["tenant_id"], unique=False
    )
    op.create_table(
        "after_sale_items",
        sa.Column("case_item_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("order_item_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("requested_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("approved_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["after_sale_cases.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("case_item_id"),
    )
    op.create_index(
        op.f("ix_after_sale_items_case_id"), "after_sale_items", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_after_sale_items_tenant_id"), "after_sale_items", ["tenant_id"], unique=False
    )
    op.create_table(
        "after_sale_status_history",
        sa.Column("history_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=True),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["after_sale_cases.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_index(
        op.f("ix_after_sale_status_history_case_id"),
        "after_sale_status_history",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_after_sale_status_history_tenant_id"),
        "after_sale_status_history",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "agent_run_steps",
        sa.Column("step_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("step_no", sa.Integer(), nullable=False),
        sa.Column("node", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=True),
        sa.Column("output_json", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("step_id"),
    )
    op.create_index(op.f("ix_agent_run_steps_run_id"), "agent_run_steps", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_agent_run_steps_tenant_id"), "agent_run_steps", ["tenant_id"], unique=False
    )
    op.create_table(
        "case_assignments",
        sa.Column("assignment_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("from_user_id", sa.String(length=36), nullable=True),
        sa.Column("to_user_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("released_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["after_sale_cases.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("assignment_id"),
    )
    op.create_index(
        op.f("ix_case_assignments_case_id"), "case_assignments", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_case_assignments_tenant_id"), "case_assignments", ["tenant_id"], unique=False
    )
    op.create_table(
        "case_comments",
        sa.Column("comment_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["after_sale_cases.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
    )
    op.create_index(op.f("ix_case_comments_case_id"), "case_comments", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_case_comments_tenant_id"), "case_comments", ["tenant_id"], unique=False
    )
    op.create_table(
        "compensation_records",
        sa.Column("compensation_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("compensation_type", sa.String(length=32), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("external_reference", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["after_sale_cases.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("compensation_id"),
    )
    op.create_index(
        op.f("ix_compensation_records_case_id"), "compensation_records", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_compensation_records_tenant_id"),
        "compensation_records",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "customer_addresses",
        sa.Column("address_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("customer_id", sa.String(length=36), nullable=False),
        sa.Column("recipient_masked", sa.String(length=128), nullable=True),
        sa.Column("phone_masked", sa.String(length=32), nullable=True),
        sa.Column("region", sa.String(length=255), nullable=True),
        sa.Column("address_ciphertext", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("address_id"),
    )
    op.create_index(
        op.f("ix_customer_addresses_tenant_id"), "customer_addresses", ["tenant_id"], unique=False
    )
    op.create_table(
        "evaluation_cases",
        sa.Column("evaluation_case_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("suite_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("expected_json", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["suite_id"],
            ["evaluation_suites.suite_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("evaluation_case_id"),
    )
    op.create_index(
        op.f("ix_evaluation_cases_suite_id"), "evaluation_cases", ["suite_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_cases_tenant_id"), "evaluation_cases", ["tenant_id"], unique=False
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("evaluation_run_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("suite_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("config_json", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["suite_id"],
            ["evaluation_suites.suite_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("evaluation_run_id"),
    )
    op.create_index(
        op.f("ix_evaluation_runs_suite_id"), "evaluation_runs", ["suite_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_runs_tenant_id"), "evaluation_runs", ["tenant_id"], unique=False
    )
    op.create_table(
        "exchange_orders",
        sa.Column("exchange_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["after_sale_cases.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("exchange_id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_index(op.f("ix_exchange_orders_status"), "exchange_orders", ["status"], unique=False)
    op.create_index(
        op.f("ix_exchange_orders_tenant_id"), "exchange_orders", ["tenant_id"], unique=False
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("knowledge_base_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_version_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.knowledge_base_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("document_id"),
        sa.UniqueConstraint("tenant_id", "knowledge_base_id", "slug", name="uq_kb_document_slug"),
    )
    op.create_index(
        op.f("ix_knowledge_documents_knowledge_base_id"),
        "knowledge_documents",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_tenant_id"), "knowledge_documents", ["tenant_id"], unique=False
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("notification_delivery_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("notification_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("provider_message_id", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.notification_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("notification_delivery_id"),
    )
    op.create_index(
        op.f("ix_notification_deliveries_notification_id"),
        "notification_deliveries",
        ["notification_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_tenant_id"),
        "notification_deliveries",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "payment_transactions",
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("payment_id", sa.String(length=36), nullable=False),
        sa.Column("transaction_type", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("provider_request_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("request_json", sa.Text(), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.payment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_index(
        op.f("ix_payment_transactions_payment_id"),
        "payment_transactions",
        ["payment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_transactions_tenant_id"),
        "payment_transactions",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "product_skus",
        sa.Column("sku_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("sku_code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("attributes_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("sku_id"),
        sa.UniqueConstraint("tenant_id", "sku_code", name="uq_skus_code"),
    )
    op.create_index(op.f("ix_product_skus_tenant_id"), "product_skus", ["tenant_id"], unique=False)
    op.create_table(
        "quality_results",
        sa.Column("result_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("rule_id", sa.String(length=36), nullable=True),
        sa.Column("score", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("findings_json", sa.Text(), nullable=False),
        sa.Column("reviewed_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["quality_rules.rule_id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["quality_tasks.task_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("result_id"),
    )
    op.create_index(
        op.f("ix_quality_results_task_id"), "quality_results", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_quality_results_tenant_id"), "quality_results", ["tenant_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("token_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("replaced_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("token_id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_tenant_id"), "refresh_tokens", ["tenant_id"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "refunds",
        sa.Column("refund_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("payment_id", sa.String(length=36), nullable=True),
        sa.Column("refund_no", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("provider_refund_no", sa.String(length=128), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("failure_message", sa.String(length=500), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["after_sale_cases.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.payment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("refund_id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_refunds_idempotency"),
        sa.UniqueConstraint("tenant_id", "refund_no", name="uq_refunds_no"),
    )
    op.create_index(op.f("ix_refunds_case_id"), "refunds", ["case_id"], unique=False)
    op.create_index(op.f("ix_refunds_status"), "refunds", ["status"], unique=False)
    op.create_index(op.f("ix_refunds_tenant_id"), "refunds", ["tenant_id"], unique=False)
    op.create_index(
        "ix_refunds_tenant_status_created",
        "refunds",
        ["tenant_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "repair_orders",
        sa.Column("repair_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["after_sale_cases.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("repair_id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_index(op.f("ix_repair_orders_status"), "repair_orders", ["status"], unique=False)
    op.create_index(
        op.f("ix_repair_orders_tenant_id"), "repair_orders", ["tenant_id"], unique=False
    )
    op.create_table(
        "reshipment_orders",
        sa.Column("reshipment_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["after_sale_cases.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("reshipment_id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_index(
        op.f("ix_reshipment_orders_status"), "reshipment_orders", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_reshipment_orders_tenant_id"), "reshipment_orders", ["tenant_id"], unique=False
    )
    op.create_table(
        "returns",
        sa.Column("return_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("return_no", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("return_address_json", sa.Text(), nullable=True),
        sa.Column("shipped_at", sa.DateTime(), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["after_sale_cases.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("return_id"),
        sa.UniqueConstraint("case_id"),
        sa.UniqueConstraint("tenant_id", "return_no", name="uq_returns_no"),
    )
    op.create_index(op.f("ix_returns_status"), "returns", ["status"], unique=False)
    op.create_index(op.f("ix_returns_tenant_id"), "returns", ["tenant_id"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("permission_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.permission_id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.role_id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "shipment_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("shipment_id", sa.String(length=36), nullable=False),
        sa.Column("event_code", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.shipment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_shipment_events_shipment_id"), "shipment_events", ["shipment_id"], unique=False
    )
    op.create_index(
        op.f("ix_shipment_events_tenant_id"), "shipment_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "shipment_items",
        sa.Column("shipment_id", sa.String(length=36), nullable=False),
        sa.Column("order_item_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.order_item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.shipment_id"],
        ),
        sa.PrimaryKeyConstraint("shipment_id", "order_item_id"),
    )
    op.create_table(
        "tool_calls",
        sa.Column("tool_call_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("step_id", sa.String(length=36), nullable=True),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("request_json", sa.Text(), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("tool_call_id"),
    )
    op.create_index(op.f("ix_tool_calls_run_id"), "tool_calls", ["run_id"], unique=False)
    op.create_index(op.f("ix_tool_calls_tenant_id"), "tool_calls", ["tenant_id"], unique=False)
    op.create_table(
        "user_credentials",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("granted_by", sa.String(length=64), nullable=False),
        sa.Column("granted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.role_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "user_id", "role_id"),
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column("delivery_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["webhook_endpoints.endpoint_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("delivery_id"),
    )
    op.create_index(
        op.f("ix_webhook_deliveries_endpoint_id"),
        "webhook_deliveries",
        ["endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_deliveries_tenant_id"), "webhook_deliveries", ["tenant_id"], unique=False
    )
    op.create_table(
        "evaluation_results",
        sa.Column("evaluation_result_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("evaluation_case_id", sa.String(length=36), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("actual_json", sa.Text(), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_case_id"],
            ["evaluation_cases.evaluation_case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["evaluation_runs.evaluation_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("evaluation_result_id"),
    )
    op.create_index(
        op.f("ix_evaluation_results_run_id"), "evaluation_results", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_results_tenant_id"), "evaluation_results", ["tenant_id"], unique=False
    )
    op.create_table(
        "knowledge_document_versions",
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.document_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("version_id"),
        sa.UniqueConstraint("document_id", "version_no", name="uq_knowledge_doc_version"),
    )
    op.create_index(
        op.f("ix_knowledge_document_versions_document_id"),
        "knowledge_document_versions",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_document_versions_tenant_id"),
        "knowledge_document_versions",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "refund_attempts",
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("refund_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("request_json", sa.Text(), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["refund_id"],
            ["refunds.refund_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("attempt_id"),
        sa.UniqueConstraint("refund_id", "attempt_no", name="uq_refund_attempt_no"),
    )
    op.create_index(
        op.f("ix_refund_attempts_refund_id"), "refund_attempts", ["refund_id"], unique=False
    )
    op.create_index(
        op.f("ix_refund_attempts_tenant_id"), "refund_attempts", ["tenant_id"], unique=False
    )
    op.create_table(
        "refund_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("refund_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=True),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["refund_id"],
            ["refunds.refund_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_refund_events_refund_id"), "refund_events", ["refund_id"], unique=False
    )
    op.create_index(
        op.f("ix_refund_events_tenant_id"), "refund_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "refund_reconciliations",
        sa.Column("reconciliation_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("refund_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("provider_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("local_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("result", sa.String(length=32), nullable=True),
        sa.Column("difference_reason", sa.String(length=500), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["refund_id"],
            ["refunds.refund_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("reconciliation_id"),
    )
    op.create_index(
        op.f("ix_refund_reconciliations_refund_id"),
        "refund_reconciliations",
        ["refund_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refund_reconciliations_tenant_id"),
        "refund_reconciliations",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "return_inspections",
        sa.Column("inspection_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("return_id", sa.String(length=36), nullable=False),
        sa.Column("inspector_id", sa.String(length=36), nullable=True),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("deduction_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("evidence_json", sa.Text(), nullable=False),
        sa.Column("inspected_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["return_id"],
            ["returns.return_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("inspection_id"),
    )
    op.create_index(
        op.f("ix_return_inspections_return_id"), "return_inspections", ["return_id"], unique=False
    )
    op.create_index(
        op.f("ix_return_inspections_tenant_id"), "return_inspections", ["tenant_id"], unique=False
    )
    op.create_table(
        "return_shipments",
        sa.Column("return_shipment_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("return_id", sa.String(length=36), nullable=False),
        sa.Column("carrier", sa.String(length=64), nullable=True),
        sa.Column("tracking_no", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["return_id"],
            ["returns.return_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("return_shipment_id"),
    )
    op.create_index(
        op.f("ix_return_shipments_return_id"), "return_shipments", ["return_id"], unique=False
    )
    op.create_index(
        op.f("ix_return_shipments_tenant_id"), "return_shipments", ["tenant_id"], unique=False
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("chunk_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=512), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding_ref", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["knowledge_document_versions.version_id"],
        ),
        sa.PrimaryKeyConstraint("chunk_id"),
        sa.UniqueConstraint("version_id", "sequence_no", name="uq_knowledge_chunk_sequence"),
    )
    op.create_index(
        op.f("ix_knowledge_chunks_tenant_id"), "knowledge_chunks", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_version_id"), "knowledge_chunks", ["version_id"], unique=False
    )
    op.create_table(
        "knowledge_index_jobs",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("backend", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["knowledge_document_versions.version_id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index(
        op.f("ix_knowledge_index_jobs_status"), "knowledge_index_jobs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_index_jobs_tenant_id"),
        "knowledge_index_jobs",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_index_jobs_version_id"),
        "knowledge_index_jobs",
        ["version_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_publications",
        sa.Column("publication_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("published_by", sa.String(length=36), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("retired_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["knowledge_document_versions.version_id"],
        ),
        sa.PrimaryKeyConstraint("publication_id"),
    )
    op.create_index(
        op.f("ix_knowledge_publications_tenant_id"),
        "knowledge_publications",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_publications_version_id"),
        "knowledge_publications",
        ["version_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_review_records",
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["knowledge_document_versions.version_id"],
        ),
        sa.PrimaryKeyConstraint("review_id"),
    )
    op.create_index(
        op.f("ix_knowledge_review_records_tenant_id"),
        "knowledge_review_records",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_review_records_version_id"),
        "knowledge_review_records",
        ["version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_knowledge_review_records_version_id"), table_name="knowledge_review_records"
    )
    op.drop_index(
        op.f("ix_knowledge_review_records_tenant_id"), table_name="knowledge_review_records"
    )
    op.drop_table("knowledge_review_records")
    op.drop_index(op.f("ix_knowledge_publications_version_id"), table_name="knowledge_publications")
    op.drop_index(op.f("ix_knowledge_publications_tenant_id"), table_name="knowledge_publications")
    op.drop_table("knowledge_publications")
    op.drop_index(op.f("ix_knowledge_index_jobs_version_id"), table_name="knowledge_index_jobs")
    op.drop_index(op.f("ix_knowledge_index_jobs_tenant_id"), table_name="knowledge_index_jobs")
    op.drop_index(op.f("ix_knowledge_index_jobs_status"), table_name="knowledge_index_jobs")
    op.drop_table("knowledge_index_jobs")
    op.drop_index(op.f("ix_knowledge_chunks_version_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_tenant_id"), table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index(op.f("ix_return_shipments_tenant_id"), table_name="return_shipments")
    op.drop_index(op.f("ix_return_shipments_return_id"), table_name="return_shipments")
    op.drop_table("return_shipments")
    op.drop_index(op.f("ix_return_inspections_tenant_id"), table_name="return_inspections")
    op.drop_index(op.f("ix_return_inspections_return_id"), table_name="return_inspections")
    op.drop_table("return_inspections")
    op.drop_index(op.f("ix_refund_reconciliations_tenant_id"), table_name="refund_reconciliations")
    op.drop_index(op.f("ix_refund_reconciliations_refund_id"), table_name="refund_reconciliations")
    op.drop_table("refund_reconciliations")
    op.drop_index(op.f("ix_refund_events_tenant_id"), table_name="refund_events")
    op.drop_index(op.f("ix_refund_events_refund_id"), table_name="refund_events")
    op.drop_table("refund_events")
    op.drop_index(op.f("ix_refund_attempts_tenant_id"), table_name="refund_attempts")
    op.drop_index(op.f("ix_refund_attempts_refund_id"), table_name="refund_attempts")
    op.drop_table("refund_attempts")
    op.drop_index(
        op.f("ix_knowledge_document_versions_tenant_id"), table_name="knowledge_document_versions"
    )
    op.drop_index(
        op.f("ix_knowledge_document_versions_document_id"), table_name="knowledge_document_versions"
    )
    op.drop_table("knowledge_document_versions")
    op.drop_index(op.f("ix_evaluation_results_tenant_id"), table_name="evaluation_results")
    op.drop_index(op.f("ix_evaluation_results_run_id"), table_name="evaluation_results")
    op.drop_table("evaluation_results")
    op.drop_index(op.f("ix_webhook_deliveries_tenant_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_endpoint_id"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_table("user_roles")
    op.drop_table("user_credentials")
    op.drop_index(op.f("ix_tool_calls_tenant_id"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_run_id"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_table("shipment_items")
    op.drop_index(op.f("ix_shipment_events_tenant_id"), table_name="shipment_events")
    op.drop_index(op.f("ix_shipment_events_shipment_id"), table_name="shipment_events")
    op.drop_table("shipment_events")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_returns_tenant_id"), table_name="returns")
    op.drop_index(op.f("ix_returns_status"), table_name="returns")
    op.drop_table("returns")
    op.drop_index(op.f("ix_reshipment_orders_tenant_id"), table_name="reshipment_orders")
    op.drop_index(op.f("ix_reshipment_orders_status"), table_name="reshipment_orders")
    op.drop_table("reshipment_orders")
    op.drop_index(op.f("ix_repair_orders_tenant_id"), table_name="repair_orders")
    op.drop_index(op.f("ix_repair_orders_status"), table_name="repair_orders")
    op.drop_table("repair_orders")
    op.drop_index("ix_refunds_tenant_status_created", table_name="refunds")
    op.drop_index(op.f("ix_refunds_tenant_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_status"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_case_id"), table_name="refunds")
    op.drop_table("refunds")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_tenant_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_quality_results_tenant_id"), table_name="quality_results")
    op.drop_index(op.f("ix_quality_results_task_id"), table_name="quality_results")
    op.drop_table("quality_results")
    op.drop_index(op.f("ix_product_skus_tenant_id"), table_name="product_skus")
    op.drop_table("product_skus")
    op.drop_index(op.f("ix_payment_transactions_tenant_id"), table_name="payment_transactions")
    op.drop_index(op.f("ix_payment_transactions_payment_id"), table_name="payment_transactions")
    op.drop_table("payment_transactions")
    op.drop_index(
        op.f("ix_notification_deliveries_tenant_id"), table_name="notification_deliveries"
    )
    op.drop_index(
        op.f("ix_notification_deliveries_notification_id"), table_name="notification_deliveries"
    )
    op.drop_table("notification_deliveries")
    op.drop_index(op.f("ix_knowledge_documents_tenant_id"), table_name="knowledge_documents")
    op.drop_index(
        op.f("ix_knowledge_documents_knowledge_base_id"), table_name="knowledge_documents"
    )
    op.drop_table("knowledge_documents")
    op.drop_index(op.f("ix_exchange_orders_tenant_id"), table_name="exchange_orders")
    op.drop_index(op.f("ix_exchange_orders_status"), table_name="exchange_orders")
    op.drop_table("exchange_orders")
    op.drop_index(op.f("ix_evaluation_runs_tenant_id"), table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_suite_id"), table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    op.drop_index(op.f("ix_evaluation_cases_tenant_id"), table_name="evaluation_cases")
    op.drop_index(op.f("ix_evaluation_cases_suite_id"), table_name="evaluation_cases")
    op.drop_table("evaluation_cases")
    op.drop_index(op.f("ix_customer_addresses_tenant_id"), table_name="customer_addresses")
    op.drop_table("customer_addresses")
    op.drop_index(op.f("ix_compensation_records_tenant_id"), table_name="compensation_records")
    op.drop_index(op.f("ix_compensation_records_case_id"), table_name="compensation_records")
    op.drop_table("compensation_records")
    op.drop_index(op.f("ix_case_comments_tenant_id"), table_name="case_comments")
    op.drop_index(op.f("ix_case_comments_case_id"), table_name="case_comments")
    op.drop_table("case_comments")
    op.drop_index(op.f("ix_case_assignments_tenant_id"), table_name="case_assignments")
    op.drop_index(op.f("ix_case_assignments_case_id"), table_name="case_assignments")
    op.drop_table("case_assignments")
    op.drop_index(op.f("ix_agent_run_steps_tenant_id"), table_name="agent_run_steps")
    op.drop_index(op.f("ix_agent_run_steps_run_id"), table_name="agent_run_steps")
    op.drop_table("agent_run_steps")
    op.drop_index(
        op.f("ix_after_sale_status_history_tenant_id"), table_name="after_sale_status_history"
    )
    op.drop_index(
        op.f("ix_after_sale_status_history_case_id"), table_name="after_sale_status_history"
    )
    op.drop_table("after_sale_status_history")
    op.drop_index(op.f("ix_after_sale_items_tenant_id"), table_name="after_sale_items")
    op.drop_index(op.f("ix_after_sale_items_case_id"), table_name="after_sale_items")
    op.drop_table("after_sale_items")
    op.drop_index(op.f("ix_after_sale_evidence_tenant_id"), table_name="after_sale_evidence")
    op.drop_index(op.f("ix_after_sale_evidence_case_id"), table_name="after_sale_evidence")
    op.drop_table("after_sale_evidence")
    op.drop_index(op.f("ix_webhook_endpoints_tenant_id"), table_name="webhook_endpoints")
    op.drop_table("webhook_endpoints")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_system_configs_tenant_id"), table_name="system_configs")
    op.drop_table("system_configs")
    op.drop_index(op.f("ix_shipments_tenant_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_order_id"), table_name="shipments")
    op.drop_table("shipments")
    op.drop_index(op.f("ix_roles_tenant_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_quality_tasks_thread_id"), table_name="quality_tasks")
    op.drop_index(op.f("ix_quality_tasks_tenant_id"), table_name="quality_tasks")
    op.drop_table("quality_tasks")
    op.drop_index(op.f("ix_quality_rules_tenant_id"), table_name="quality_rules")
    op.drop_table("quality_rules")
    op.drop_index(op.f("ix_products_tenant_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_payments_tenant_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_payment_callbacks_tenant_id"), table_name="payment_callbacks")
    op.drop_table("payment_callbacks")
    op.drop_index(op.f("ix_outbox_events_tenant_id"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_status"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_index("ix_outbox_available", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_order_status_history_tenant_id"), table_name="order_status_history")
    op.drop_index(op.f("ix_order_status_history_order_id"), table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index(op.f("ix_order_items_tenant_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_order_addresses_tenant_id"), table_name="order_addresses")
    op.drop_index(op.f("ix_order_addresses_order_id"), table_name="order_addresses")
    op.drop_table("order_addresses")
    op.drop_index(op.f("ix_oidc_connections_tenant_id"), table_name="oidc_connections")
    op.drop_table("oidc_connections")
    op.drop_index(op.f("ix_notifications_tenant_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_recipient_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_message_feedback_tenant_id"), table_name="message_feedback")
    op.drop_index(op.f("ix_message_feedback_message_id"), table_name="message_feedback")
    op.drop_table("message_feedback")
    op.drop_index(op.f("ix_message_attachments_tenant_id"), table_name="message_attachments")
    op.drop_index(op.f("ix_message_attachments_message_id"), table_name="message_attachments")
    op.drop_table("message_attachments")
    op.drop_index(op.f("ix_knowledge_bases_tenant_id"), table_name="knowledge_bases")
    op.drop_table("knowledge_bases")
    op.drop_index(op.f("ix_inbox_events_tenant_id"), table_name="inbox_events")
    op.drop_table("inbox_events")
    op.drop_index(op.f("ix_idempotency_records_tenant_id"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_human_handoff_tasks_thread_id"), table_name="human_handoff_tasks")
    op.drop_index(op.f("ix_human_handoff_tasks_tenant_id"), table_name="human_handoff_tasks")
    op.drop_table("human_handoff_tasks")
    op.drop_index(op.f("ix_feature_flags_tenant_id"), table_name="feature_flags")
    op.drop_table("feature_flags")
    op.drop_index(op.f("ix_evaluation_suites_tenant_id"), table_name="evaluation_suites")
    op.drop_table("evaluation_suites")
    op.drop_index(op.f("ix_customers_tenant_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_approval_records_tenant_id"), table_name="approval_records")
    op.drop_index(op.f("ix_approval_records_task_thread_id"), table_name="approval_records")
    op.drop_table("approval_records")
    op.drop_index(op.f("ix_approval_definitions_tenant_id"), table_name="approval_definitions")
    op.drop_table("approval_definitions")
    op.drop_index(op.f("ix_agent_runs_thread_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_tenant_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_cases_tenant_status_created", table_name="after_sale_cases")
    op.drop_index(op.f("ix_after_sale_cases_tenant_id"), table_name="after_sale_cases")
    op.drop_index(op.f("ix_after_sale_cases_status"), table_name="after_sale_cases")
    op.drop_index(op.f("ix_after_sale_cases_order_id"), table_name="after_sale_cases")
    op.drop_index(op.f("ix_after_sale_cases_case_type"), table_name="after_sale_cases")
    op.drop_table("after_sale_cases")
    op.drop_index(op.f("ix_tenants_status"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_code"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_permissions_code"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_login_events_user_id"), table_name="login_events")
    op.drop_index(op.f("ix_login_events_tenant_id"), table_name="login_events")
    op.drop_index(op.f("ix_login_events_outcome"), table_name="login_events")
    op.drop_index(op.f("ix_login_events_created_at"), table_name="login_events")
    op.drop_table("login_events")
    # ### end Alembic commands ###
